name: CI/CD Pipeline demo
on:
  push:
    branches: [ master ]
jobs:       
  deploy:
    runs-on: ubuntu-latest
     # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      # Step 1
    - name: Checkout to repo
      uses: actions/checkout@v2

      # Step 2 
    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-session-token:  ${{secrets.AWS_SESSION_TOKEN}}
       aws-region: us-east-1

#  Step 2
#     - name: Set AWS credentials
#       uses: aws-actions/configure-aws-credentials@v2
#       with:
#         role-to-assume: arn:aws:iam::530095765619:role/LabRole
#         aws-region: us-east-1

      # Step 3
    - name: Create CodeDeploy Deployment
      id: deploy
      run: |
        aws deploy create-deployment \
        --application-name nodejs-express-app \
        --deployment-group-name nodejs-express-app-cd1 \
        --deployment-config-name CodeDeployDefault.OneAtATime \
        --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
